### PR TITLE
Replace hardcoded -j16 argument for make, oe_runmake and ninja with ${PARALLEL_MAKE}

### PR DESCRIPTION
**Pull request by MCherifiOSS**
Original pull request with technical discussions: https://github.com/konsulko/tizen-distro/pull/1

I have just revert replacement of oe_runmake by make in some Yocto recipes in this new pull request.

The idea if to avoid hard-codded values and let Yocto to adapt them with the build machine capacities.

In some cases with low capacities machines, we have found that CrossWalk recipes failed to build using "ninja -j16", more details are here: https://bugs.tizen.org/jira/browse/BTY-102

### CODE REVIEW

**Comment by leon-anavi** [comment]
Hi Mohammed, thank you for your contribution. I noticed that you have replaced -j1 (not -j16) with ${PARALLEL_MAKE} in the following files: capi-system-sensor.inc, vala.inc, libmm-player.inc. Is it safe and does it lead to any side effects?

**Comment by mchehab** [comment]
Hi Mohammed,

I double checked on poky: no packages there use ${PARALLEL_MAKE} for make/oe_runmake commands. I also double-checked that bitbake adds it automatically if not specified.
here (where I have 32 CPUs on my build machine), I even get those warnings while building packages with "make -j16":

NOTE: make -j 32 -j16

So, I think that the right fix here is, actually:
- oe_runmake -j16
+ oe_runmake

\- make -j16
+ make

Not sure about ninja.

**Comment by trini** [comment]
Ah yes, oe_runmake includes PARALLEL_MAKE, that slipped my mind for a moment.  But we still want to correct direct invocations of 'make' to be oe_runmake and if any of the recipes are racy internally (and we can't just _fix_ that) then we kludge them down to -j1 and make a note about where the problem lies.

**Comment by leon-anavi** [comment]
Hi Mohammed, Tom, Mauro,

Thank you all for your valuable comments. Mauro has submitted a patch that removes -j16 from all recipes. It is waiting to be merged with the upstream. You can do a code review of his change:
https://review.tizen.org/gerrit/#/c/41233/

Regarding these circumstances I will close this push request without merging it. When Mauro's patch for -j16 is merged with the upstream of "Tizen on Yocto" I will also apply it to this repository.

**Comment by MCherifiOSS** [comment]
Hi Leon, Mauro, Tom,
Perfect, I agree. It's a better idea to take to Mauro's patch.
As I see, the upstream of "Tizen on Yocto" is not actively maintened! Maybe we have to give some help!

Thank you all.

Mohammed

**Comment by leon-anavi** [comment]
Hi Mohammed,

Thank you for your understanding and collaboration. I hope that in near future the upstream of "Tizen on Yocto" will be transferred to Mauro and I volunteered to help as a co-maintainer. There was an announcement about "Tizen on Yocto" at the Dev mailing list couple hours ago (btw please join this mailing list if you have not done it already).

Thanks,
Leon

**Comment by MCherifiOSS** [comment]
Hi Leon,

I just signed up the mailing list.
I would like to help you to maintain this repo.
Let me know if you need some help.

Mohammed

**Pull request closed without merging**
