### PR TITLE
 	Replace the -j16 parameter for make, ninja and other commands by in Yocto receipes to avoid some compilation errors and optimize build time

### PR DESCRIPTION
**Pull request by MCherifiOSS**
For instance, CrossWalk packages failed to build on PCs with CPUs like Intel Core2Duo or Intel Core i3/i5
https://bugs.tizen.org/jira/browse/BTY-102

### CODE REVIEW

**Comment by trini** [comment]
Please clarify the commit message slightly.  Replacing -j16 with ${PARALLEL_MAKE} simply changes the number used and that may hide parallel make problems but doesn't fix them.  Also in some cases you replace oe_runmake with make which is incorrect, we want to keep using oe_runmake (and the example you see which call make directly should be updated while we're in here).

**Comment by MCherifiOSS** [comment]
Yes of course. Replace some oe_runmake by make this is due to merge what I did with tizen-ivi branch from git: //review.tizen.org/scm/bb/tizen-distro. However, you're right, it's better to use oe_runmake. Regarding the replacement of -j16 by $ {} PARALLEL_MAKE in my opinion it's better than hardcoded value because we will use the best number of CPUs available mainly for build servers with higher CPU Cores and for the machines less powerful like the dual core CPUs, we find that it cause compilation issues for CrossWalk using ninja command.
If you want more information: https://bugs.tizen.org/jira/browse/BTY-102

**Comment by MCherifiOSS** [comment]
If it's OK for you, I can revert the replacement of oe_runmake by make and clarify more the commit message!

**Comment by trini** [comment]
Yes, changing from -j16 to a configurable variable is correct.  Note that normally when one says a package fails to build due to a "make -j N" type problem it's due to a race condition within the build and dependencies being improperly expressed.  Now that I look at BTY-102 it's due to simply overloading the machine and then yes PARALLEL_MAKE will be automatically set to something much lower and more appropriate for those machines which means that we don't end up causing an OOM or similar on the build machine.  A good and correct fix all around :)

**Pull request closed without merging**
